assets/urls.py
#  portfolio/urls.py

from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path('', views.hero_page_view, name='hero'),
    path('home', views.about_page_view, name='home'),
    path('about', views.about_page_view, name='about'),
    path('web', views.web_page_view, name='web'),
    path('quizz', views.quizz, name='quizz'),
    path('contactos', views.contactos_page_view, name='contactos'),

    path('blog', views.blog_page_view, name='blog'),
    path('novo/', views.novo_comentario_view, name='novo'),
    path('edita/<int:comentario_id>', views.edita_comentario_view, name='edita'),
    path('apaga/<int:comentario_id>', views.apaga_comentario_view, name='apaga'),
]

assets/models.py
from django.db import models

# Create your models here.


class Portfolio(models.Model):
    nome = models.CharField(max_length=100)
    comentario = models.CharField(max_length=600)
    criado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nome[:50]


class PontuacaoQuizz(models.Model):
    nome = models.CharField(max_length=64)
    pontuacao = models.IntegerField(max_length=10)


class Linguagem(models.Model):
    nome = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.nome}"



class Professor(models.Model):
    nome = models.CharField(max_length=64)
    numero = models.IntegerField(max_length=10)

    def __str__(self):
        return f"{self.nome}({self.numero})"


class Projeto(models.Model):
    nome = models.CharField(max_length=64)


    def __str__(self):
        return f"{self.nome}({self.id})"


class Cadeira(models.Model):
   nome = models.CharField(max_length=20)
   ano = models.IntegerField()
   descricao = models.TextField()
   linguagens = models.ManyToManyField(Linguagem)
   docente_teorica = models.ForeignKey(Professor, on_delete=models.CASCADE)
   docentes_praticas = models.ManyToManyField(Professor, related_name='caderias')
   projetos = models.ManyToManyField(Projeto)

assets/forms.py
from django import forms
from django.forms import ModelForm
from .models import Portfolio


class PortfolioForm(ModelForm):
    class Meta:
        model = Portfolio
        fields = '__all__'
        # inserção de classes CSS para formatação de cada campo do formulário
        widgets = {
            'nome': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Insira o nome a aparecer como autor...'}),
            'comentario': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Escreva aqui o seu comentário...'}),
        }

        # texto a exibir junto à janela de inserção
        labels = {
            'nome': 'Nome',
            'comentario': 'Comentario',
        }

        # texto auxiliar a um determinado campo do formulário
        help_texts = {
            'nome': 'Escreva "Anónimo" caso não queira deixar o seu nome',
        }

assets/views.py
#  hello/views.py

import datetime
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Portfolio, PontuacaoQuizz
from .forms import PortfolioForm


def home_page_view(request):
    agora = datetime.datetime.now()
    local = 'Lisboa'
    topicos = ['HTML', 'CSS', 'Python', 'Django', 'JavaScript']

    context = {
        'hora': agora.hour,
        'local': local,
        'topicos': topicos,
    }
    return render(request, 'home.html', context)


def about_page_view(request):
    agora = datetime.datetime.now()
    local = 'Lisboa'
    topicos = ['HTML', 'CSS', 'Python', 'Django', 'JavaScript']

    context = {
        'hora': agora.hour,
        'local': local,
        'topicos': topicos,
    }
    return render(request, 'about.html', context)


def web_page_view(request):
    return render(request, 'web.html')

def contactos_page_view(request):
    return render(request, 'contactos.html')


def projetos_page_view(request):
    return render(request, 'projetos.html')


def hero_page_view(request):
    return render(request, 'hero.html')


def blog_page_view(request):
    context = {'comentarios': Portfolio.objects.all()}
    return render(request, 'blog.html', context)


def novo_comentario_view(request):
    form = PortfolioForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))
    context = {'form': form}
    return render(request, 'novo.html', context)


def edita_comentario_view(request, comentario_id):
    comentario = Portfolio.objects.get(id=comentario_id)
    form = PortfolioForm(request.POST or None, instance=comentario)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))

    context = {'form': form, 'comentario_id': comentario_id}
    return render(request, 'edita.html', context)


def apaga_comentario_view(request, comentario_id):
    Portfolio.objects.get(id=comentario_id).delete()
    return HttpResponseRedirect(reverse('projeto:blog'))


def pontuacao_quizz(request):
    return request.pontuacao


def quizz(request):
    if request.method == 'POST':
        n = request.POST['nome']
        p = pontuacao_quizz(request)
        r = PontuacaoQuizz(nome=n, pontuacao=p)
        r.save()
    return render(request, 'quizz.html')

assets/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Me</title>

    <link rel="stylesheet" href="../../assets/static/portfolio/css/about.css">


    <link rel="icon" type="image/x-icon"
          href="https://yt3.ggpht.com/ytc/AKedOLTtSIICccWIydxNZ3Cj3QQFukp2OukrFVzoXIdI=s600-c-k-c0x00ffffff-no-rj-rp-mo"/>

</head>

<body>
<header id="main-header">
    <p>Tomé Roque</p>
    <nav>
        <a href="../../index.html">Home</a>
        <a href="about.html">About Me</a>
        <a href="{% url 'portfolio:blog' %}">Projects</a>
        <a href="{% url 'portfolio:quizz' %}">Contact</a>
    </nav>
</header>

<div id="grad1">
    <div id="gradup"></div>
</div>

<div class="container">
    <img src="../../assets/static/portfolio/images/aboutImage.png" alt="Article Image">
    <div class="text">
        <h1>Who am I?</h1>
        <p id="age-paragraph"></p>
        <p>
            Always connected to all kinds of activities, ranging from football, to theater,
            to volunteering, all the way to coding, where I have found my most recent passion.
            Having been in this virtual environment since starting my journey at university and
            picking up some projects along the way that led me to who I am today.
            Throughout my journey, I have learned the importance of Cooperation, Correlation and
            Coexistence as well as life and work ethics. I am a very dedicated person, always
            giving my all on the activity I'm working on.

        </p>
        <p>If you are interested on my work, don't hesitate to contact me:</p>

        <div class="profile-container">
            <div class="contact">
                <a href="https://www.linkedin.com/in/tom%C3%A9-roque-774752182/" target="_blank">
                    <img src="../../assets/static/portfolio/images/linkedin.png" alt="LinkedIn Icon" class="icon-image" id="firstImage">
                    <span class="name">Tomé Roque</span>
                </a>
            </div>
            <div class="contact">
                <a href="mailto:tome.roque09@gmail.com">
                    <img src="../../assets/static/portfolio/images/gmail.png" alt="Email Icon" class="icon-image">
                    <span class="email">tome.roque09@gmail.com</span>
                </a>
            </div>
        </div>

    </div>


</div>
<div class="container" id="personalAbilities">
    <div class="object-container" onclick="showInfo('object1')">
        <img id="career" src="../../assets/static/portfolio/images/aboutIcons/carreira-notSelected.png" alt="Object 1">
        <p>Career</p>
    </div>

    <div class="object-container" onclick="showInfo('object2')">
        <img id="cumputing" src="../../assets/static/portfolio/images/aboutIcons/uni-notSelected.png" alt="Object 2">
        <p>Computing Engeneering</p>
    </div>

    <div class="object-container" onclick="showInfo('object3')">
        <img id="editor" src="../../assets/static/portfolio/images/aboutIcons/editor-notSelected.png" alt="Object 3">
        <p>Editor</p>
    </div>
    <div class="object-container" onclick="showInfo('object4')">
        <img id="skills" src="../../assets/static/portfolio/images/aboutIcons/skills-notSelected.png" alt="Object 4">
        <p>Personal Skills</p>
    </div>


</div>
    <div class="info-container" id="info">
        <iframe src="" frameborder="0" width="100%" height="600" id="frame"></iframe>
    </div>

</body>

<script src="../../assets/static/portfolio/js/script.js"></script>

</html>

assets/templates/aboutPages/career.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Career</title>
    <link rel="stylesheet" href="../../../assets/static/portfolio/css/career.css">
</head>
<body>

    <div class="container">
        <div class="column">
            <img src="../../../assets/static/portfolio/images/omera.png" alt="Image 1">
            <p><h2>OMERA</h2> Android developer</p>
        </div>
        <div class="column">
            <img src="../../../assets/static/portfolio/images/icon.jpg" alt="Image 2">
            <p><h2>My website</h2> HTML, CSS and JS</p>
        </div>
        <div class="column">
            <img src="../../../assets/static/portfolio/images/noraya.png" alt="Image 3">
            <p><h2>Noraya</h2> Video editing</p>
        </div>
        <div class="column">
            <img src="../../../assets/static/portfolio/images/pumpaddicted.jpg" alt="Image 4">
            <p><h2>PumpAddicted Health & Fitness</h2> Podcast editing and content creator</p>
        </div>
        <div class="column">
            <img src="../../../assets/static/portfolio/images/lourinha.jpg" alt="Image 5">
            <p><h2>Câmara Municipal da Lourinhã</h2> Image and video editing, website maintenance</p>
        </div>
    </div>

</body>
</html>

assets/templates/aboutPages/uni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../../../assets/static/portfolio/css/uni.css">
    <title>University</title>
</head>
<body>

<div class="container" id="titulo">
    <div class="image">
        <img src="../../../assets/static/portfolio/images/uni-subjects/lusofona-logo.png" alt="Image">
    </div>
    <div class="text">
        <h2>Degree in Computing Engeneering</h2>
        <p>@ Universidade Lusófona de Humanidades e Tecnologias</p>
    </div>
</div>

<h1>1st Year</h1>

<div class="container">
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/kotlin.png" alt="Image 1">
        <p>
        <h2>Programming Fundamentals</h2> Kotlin programming</p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/maths.png" alt="Image 2">
        <p>
        <h2>Math I</h2></p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/discrete.jpg" alt="Image 3">
        <p>
        <h2>Discrete Mathematics</h2></p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/digital.jpg" alt="Image 4">
        <p>
        <h2>Digital Systems</h2></p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/fisics.png" alt="Image 5">
        <p>
        <h2>Fisics</h2></p>
    </div>

    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/cc.jpg" alt="Image 1">
        <p>
        <h2>Behavioral skills</h2> Presentation coaching</p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/LPI.png" alt="Image 2">
        <p>
        <h2>Programming Languages I</h2> C programming</p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/algebra.jpg" alt="Image 3">
        <p>
        <h2>Linear Algebra</h2></p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/maths.png" alt="Image 4">
        <p>
        <h2>Math II</h2></p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/AC.jpg" alt="Image 5">
        <p>
        <h2>Computer Arquitecture</h2></p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/aed.png" alt="Image 5">
        <p>
        <h2>Data Algorithms & Structures</h2></p>
    </div>
</div>






<h1>2nd Year</h1>

<div class="container">
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/java.png" alt="Image 1">
        <p>
        <h2>Programming Languages II</h2> Java programming</p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/databases.png" alt="Image 2">
        <p>
        <h2>Data Bases</h2></p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/AC2.png" alt="Image 3">
        <p>
        <h2>Advanced Computer Arquitectures</h2></p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/statistics.png" alt="Image 4">
        <p>
        <h2>Statistics and Probability</h2></p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/os.jpg" alt="Image 5">
        <p>
        <h2>Operating Systems</h2></p>
    </div>

    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/web.png" alt="Image 1">
        <p>
        <h2>Web Programming</h2> HTML, CSS, Django & JavaScript</p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/cn.jpg" alt="Image 2">
        <p>
        <h2>Computer Networking</h2></p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/gc.png" alt="Image 3">
        <p>
        <h2>Computer Graphics</h2></p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/re.png" alt="Image 5">
        <p>
        <h2>Requirements Engineering</h2></p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/dss.png" alt="Image 5">
        <p>
        <h2>Decision Support Systems</h2></p>
    </div>
</div>








<h1>3rd Year</h1>

<div class="container">
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/ihm.jpg" alt="Image 1">
        <p>
        <h2>Human-Machine Interaction</h2></p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/data.jpeg" alt="Image 2">
        <p>
        <h2>Data Science</h2></p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/software.jpg" alt="Image 3">
        <p>
        <h2>Software Engeneering</h2></p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/cd.jpg" alt="Image 4">
        <p>
        <h2>Distributed Computing</h2>Web Services</p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/movel.png" alt="Image 5">
        <p>
        <h2>Mobile Computing</h2>Android & Flutter</p>
    </div>

    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/seguranca.png" alt="Image 1">
        <p>
        <h2>Computer Security</h2></p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/ai.jpg" alt="Image 2">
        <p>
        <h2>Artificial Intelligence</h2></p>
    </div>
    <div class="column">
        <img src="../../../assets/static/portfolio/images/uni-subjects/cloud.png" alt="Image 3">
        <p>
        <h2>Cloud Information Systems</h2></p>
    </div>
</div>

</body>
</html>

assets/templates/blog.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block main %}
    {% for comentario in portfolio %}
        <p> 
           {{ comentario.nome }}
           <a href="{% url 'portfolio:edita' comentario.id %}" class="btn btn-warning">Editar comentário</a>
        </p>
   {% endfor %}
        <a href="{% url 'portfolio:novo' %}" class="btn btn-success btn-block">Novo comentário</a>
{% endblock %}

assets/templates/contactos.html
{% extends 'portfolio/layout.html' %}

{% load static %}

{% block title %}Web{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'portfolio/css/contactos.css' %}">



{% endblock %}


{% block main %}

<h1>Contactos</h1>

<p><a href="https://www.linkedin.com/in/tom%C3%A9-roque-774752182">LinkedIn</a> <br>
<br><a href="https://github.com/TomeRoque-21807126">github</a> <br>
<br>a21807126@alunos.ulht.pt<br><br> from Torres Vedras</p>


{% endblock %}

assets/templates/edita.html
{% extends 'tarefas/base.html' %}

{% load static %}

{% block main %}
<h3>Comentário</h3>
    <form action="{% url 'portfolio:edita' comentario_id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'portfolio:blog' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
        <a href="{% url 'portfolio:apaga' comentario_id %}" role="button" class="btn btn-danger">Apagar</a>
    </form>

{% endblock %}

assets/templates/hero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bem vindo!</title>

  {% load static %}
  <link rel="stylesheet" href="{% static 'portfolio/css/hero.css' %}">

  <link rel="icon" type="image/x-icon" href="https://yt3.ggpht.com/ytc/AKedOLTtSIICccWIydxNZ3Cj3QQFukp2OukrFVzoXIdI=s600-c-k-c0x00ffffff-no-rj-rp-mo"/>

</head>

<body>
  <header>
    <p>Tomé Roque</p>
    <nav>
      <a href="{% url 'portfolio:hero' %}">Home</a>
      <a href="{% url 'portfolio:about' %}">About Me</a>
      <a href="{% url 'portfolio:blog' %}">Blog</a>
      <a href="{% url 'portfolio:quizz' %}">Quizz</a>
      <a href="{% url 'portfolio:web' %}">Web</a>
      <a href="{% url 'portfolio:contactos' %}">Contactos</a>

    </nav>
  </header>

  <main>
    <p>Welcome to my Digital Portfolio!</p>
  </main>

  <article class="primeiro">
    <p><b><i>Meet Tomé Roque.</i></b> Programmer & Editor <br><br>
    Hey there! As you already know, my name is Tomé Roque. A small town boy who grew up to take a degree in computer science
      while also having a passion for photo and video editing, having been involved in projects on both matters. <br>
      Living in a world where people should enjoy what they do, I also make some of my own work mainly for fun purposes.
      Have a look around my website and discover them for yourselves!
    </p>
  </article>

  <article class='segundo'>
  </article>

  <footer>
    <p>Tomé Roque ♠ Website desenvolvido em 2022</p>

  </footer>
</body>

</html>

assets/templates/home.html
{% extends 'portfolio/layout.html' %}

{% load static %}
<link rel="stylesheet" href="{% static 'portfolio/css/base.css' %}">


<link rel="stylesheet" href="../static/portfolio/css/base.css">

{% block main %}
	<h3>Bem Vindo!</h3>
    <p>Eu sou o Tomé Roque, e este é o meu portfolio!</p>

    {% load static %}
    <img src="{% static 'portfolio/images/image.png' %}">
{% endblock %}


assets/templates/novo.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block main %}
<h3>Novo Comentário</h3>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'portfolio:blog' %}" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
    </form>
{% endblock %}

assets/templates/portfolio/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Comentários</title>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎯</text></svg>">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/css/blog.css' %}">
</head>
<body>
<header class="menu">
    <p class="nomeMenu">Tomé Roque</p>
    <nav class="hrefMenu">
      <a href="{% url 'portfolio:hero' %}">Home</a>
      <a href="{% url 'portfolio:about' %}">About Me</a>
      <a href="{% url 'portfolio:blog' %}">Blog</a>
      <a href="{% url 'portfolio:quizz' %}">Quizz</a>
        <a href="{% url 'portfolio:web' %}">Web</a>
        <a href="{% url 'portfolio:contactos' %}">Contactos</a>
    </nav>
  </header>

    <header class="jumbotron text-center">
        <h1>Comments</h1>
        <hr width="30%">
        <p>Leave a comment, tips are always welcome!</p>
    </header>

    <main class="container text-center">
    {% block main %}

    {% endblock %}
    </main>
    <footer>Portfólio Tomé Roque - ULHT</footer>
</body>
</html>

assets/templates/portfolio/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>{% block title %}{% endblock %}</title>




    <link rel="icon" type="image/x-icon" href="https://yt3.ggpht.com/ytc/AKedOLTtSIICccWIydxNZ3Cj3QQFukp2OukrFVzoXIdI=s600-c-k-c0x00ffffff-no-rj-rp-mo"/>


    <link rel="stylesheet" href="{% static 'portfolio/css/layout.css' %}">
    {% block styles %}

    {% endblock %}


</head>
<body>
  <header>
    <div>Tomé Roque</div>
    <nav>
      <a href="{% url 'portfolio:hero' %}">Home</a>
      <a href="{% url 'portfolio:about' %}">About Me</a>
      <a href="{% url 'portfolio:blog' %}">Blog</a>
        <a href="{% url 'portfolio:quizz' %}">Quizz</a>
      <a href="{% url 'portfolio:web' %}">Web</a>
        <a href="{% url 'portfolio:contactos' %}">Contactos</a>

    </nav>
  </header>

  <main>
	{% block main %}
	{% endblock main %}
  </main>

  <body>
  {% block body %}

  {% endblock body %}
  </body>
  <footer>
      <div><p>Tomé Roque ♠ Website desenvolvido em 2022</p></div>
  </footer>
</body>
</html>

assets/templates/projetos.html
{% extends 'portfolio/layout.html' %}

{% block main %}



{% endblock %}

assets/templates/quizz.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bem vindo!</title>

  {% load static %}
  <link rel="stylesheet" href="{% static 'portfolio/css/quizz.css' %}">

    <link rel="stylesheet" href="../static/portfolio/css/quizz.css">

</head>

<body>
  <header>
    <p>Tomé Roque</p>
    <nav>
      <a href="{% url 'portfolio:hero' %}">Home</a>
      <a href="{% url 'portfolio:about' %}">About Me</a>
      <a href="{% url 'portfolio:blog' %}">Blog</a>
      <a href="{% url 'portfolio:quizz' %}">Quizz</a>
        <a href="{% url 'portfolio:web' %}">Web</a>
        <a href="{% url 'portfolio:contactos' %}">Contactos</a>
    </nav>
  </header>


<section>
        <h3>Quizz</h3>
        <p>In this page you will be tested about you knollege on html</p>

        <form method="POST">
            <fieldset>
                On HTML
            <fieldset>
                <title>info</title>
                <input type="text" name="nome" placeholder="insira o seu nome">
                <br>
            </fieldset>
            </fieldset>

            <fieldset>
                <title>Questions</title>
                <label><b>Question 1:</b> HTML stands for...</label>
                <br>
                <input type="radio" id="pais1" name="pais" value="portugal"><label for="pais1"> High Tension Multimedia LANs</label><br>
                <input type="radio" id="pais2" name="pais" value="espanha"><label for="pais2"> HyperText Markup Language</label><br>
                <input type="radio" id="pais3" name="pais" value="brasil"><label for="pais3"> HardText Makeup Language</label>
                <br>
                <br>
                <label><b>Question 2:</b> HTML is a language used mainly for <input type="text" id="emisferio" name="emisferio" placeholder="games / websites / data bases / cicles"><label for="emisferio"></label></label>
                <br>
                <br>
                <label><b>Question 3:</b> Django has support for:</label><br>
                <input type="checkbox" id="known1" name="known1" value="praia"><label for="known1">inherit</label><br>
                <input type="checkbox" id="known2" name="known2" value="chuva"><label for="known2">Cicles</label><br>
                <input type="checkbox" id="known3" name="known3" value="mare"><label for="known3">Load static files</label><br>
                <input type="checkbox" id="known4" name="known4" value="turismo"><label for="known4">couple of drinks</label><br>
                <input type="checkbox" id="known5" name="known5" value="calor"><label for="known5">I dont even know anymore</label><br>
                <br>
                <br>
                <textarea id="comentario" name="comentario" rows="4" cols="50" placeholder="Escreva um Comentário"></textarea>
                <br>
                <br>

                <input type="submit">
            </fieldset>
        </form>
    </section>






<footer>
    <p>Tomé Roque ♠ Website desenvolvido em 2022</p>

  </footer>

</body>
</html>

assets/templates/web.html
{% extends 'portfolio/layout.html' %}

{% load static %}

{% block title %}Web{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'portfolio/css/web.css' %}">



{% endblock %}


{% block main %}

<div id="grad1"><div id="gradup"></div></div>

<h1>Sobre este Website<br></h1>

<div id="diagrama">

    <img src="{% static 'portfolio/images/diagrama.png' %}">

</div>

<h1> Estrutura do site </h1>

<iframe width="560" height="315" src="https://www.youtube.com/embed/g1DsE_qHw9s" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>



<p>Em ciência da computação, front-end, interface frontal ou parte frontal e back-end, parte secundária, parte de suporte ou parte de retaguarda são termos generalizados que se referem às etapas inicial e final de um processo. O front-end é responsável por coligir a entrada do usuário em várias formas e processá-la para adequá-la a uma especificação em que o back-end a possa utilizar.
    <br></p>
<h2>Algumas tecnologias para web front-end e back-end</h2>
<h3>Front-end</h3>
<p>React<br>
XHTML<br>
HTML5<br>
CSS<br>
Javascript<br>
AJAX<br>
jQuery<br>
CFML<br>
AngularJS<br>
Angular<br>
    Vue<br></p>
<h2>Back-end</h2>
<p>PHP<br>
C<br>
C++<br>
Node.js<br>
Ruby on Rails<br>
Python<br>
Java<br>
JSP<br>
.NET<br>
C♯<br>
VB<br>
Perl Catalyst<br></p>
<p style="colour: grey">Texto retirado do wikipedia</p>
{% endblock %}